import Footer from "~/components/footer/Footer"
import Navbar from "~/components/Navbar/Navbar"

const termsConditions = () => {
    return (
        <>
            <Navbar />
            <div className="relative">
                <img src="/images/bg/policy-bg-5.webp" alt="Loading..." className="-z-10 w-full" />
                <h1 className="absolute top-[41%] left-[2.5rem] text-6xl font-bold max-sm:text-4xl max-[450px]:text-2xl"><span className="text-[#00a181]">Terms</span>  & Conditions</h1>
            </div>
            <div className="px-20 py-4 text-gray-700 text-base font-normal max-md:px-10">
                <p className="mb-2">By downloading, browsing, accessing or using this VIDYUTVA mobile application (“Mobile Application”), you confirm that you have read, understood and agree to be bound by these Terms and Conditions of Use. You must ensure read the Terms of use carefully before downloading, registering, accessing, browsing, or using the mobile application. We reserve the right to amend these terms and conditions at any time. If you disagree with any of these Terms and Conditions of Use, you must immediately discontinue your access to the Mobile Application and your use of the services offered on the Mobile Application (“Services”) and the charging services. Continued use of the Mobile Application will constitute acceptance of these Terms and Conditions of Use, as may be amended from time to time.</p>
                <p className="my-4">If you create an account in the Mobile Application, you are responsible for maintaining the security of your account and you are fully responsible for all activities that occur under the account and any other actions taken in connection with it. The VIDYUTVA mobile application Services are not available to persons under the age of 18 or to anyone previously suspended or removed by Vidyutva Technology Private Limited from availing its Services or accessing the VIDYUTVA Platform. By accepting the T&Cs or by otherwise using the VIDYUTVA Services on its Platform, you represent that you are at least 18 years of age and have not been previously suspended or removed by Vidyutva Technology Private Limited , or disqualified for any other reason, from availing the VIDYUTVA Services offered or using the VIDYUTVA Platform.</p>
                <p className="my-4">In the event that any user ID and/or password is used by you or issued to you by us during the process of your signing up to be a user/member of the Mobile Application, you shall protect the secrecy of such user ID and/or password at all times and shall ensure that the user ID and/or password is not revealed or disclosed in any manner whatsoever to any person. You should change your password from time to time to enhance its security. You shall be fully responsible for all use and liability resulting from access to this Mobile Application with your user ID and/or password. We shall not be responsible for unauthorized transactions incurred by you arising from or in connection with the misuse or disclosure of your user ID and/or password. In addition, you represent and warrant that you have the right, authority and capacity to enter into this Agreement for use of the services and to abide by all the T&Cs as part of these terms.</p>
                <p className="my-4">Any passwords or rights given to you to obtain information or other contents are not transferable and may only be used by you. You must keep your password confidential and immediately notify us if any unauthorized third party becomes aware of that password or if there is any unauthorized use of your email address or any breach of security is known to you. You agree that any person to whom your user name or password is disclosed is authorized to act as your agent for the purposes of using (and/or transacting via) the Services, and Mobile Application. Maintenance of the confidentiality of your password is your responsibility.</p>
                <p className="my-4">If you suspect that your password has been compromised in any manner, you shall immediately inform us and change your password. We may, but have no obligation to, monitor and review new accounts before you may sign in and use our Services. Providing false contact information of any kind may result in the termination of your account. You must immediately notify us of any unauthorized uses of your account or any other breaches of security. We will not be liable for any acts or omissions by you, including any damages of any kind incurred as a result of such acts or omissions by you.</p>
                <p className="my-4">Finally, you shall not impersonate any person or entity, or falsely state or otherwise misrepresent your identity, age or affiliation with any person or entity. In the event of any violation of the T&Cs, Vidyutva Technology Private Limited reserves the right to suspend or permanently prevent you from availing VIDYUTVA Services or using the VIDYUTVA Platform.</p>
                <p className="my-4">Although this Mobile Application may link to other third party mobile applications, we are not, directly or indirectly, implying any approval, association, sponsorship, endorsement, or affiliation with any linked third party mobile application, unless specifically stated herein. We are not responsible for examining or evaluating, and we do not warrant the offerings of, any businesses or individuals or the content of their mobile applications. We do not assume any responsibility or liability for the actions, products, services, and content of any other third-parties. Vidyutva Technology Private Limited does not implicitly or explicitly support or endorse the sale or purchase of any products and services of the third party mobile application. Vidyutva Technology Private Limited accepts no liability for any errors or omissions of third parties mobile applications in relation to the products and services You should carefully review the legal statements and other conditions of use of any mobile application which you access through a link from this Mobile Application. Linking of the Mobile Application to any other mobile applications is at your own risk.</p>
                <div className="my-4">
                    <p>In addition to other terms as set forth in the Agreement, you are prohibited from using the Mobile Application or its Content:</p>
                    <ol className="pl-8 list-[lower-alpha]">
                        <li>For any unlawful purpose.</li>
                        <li>To solicit others to perform or participate in any unlawful acts.</li>
                        <li>To violate any international, federal, provincial or state regulations, rules, laws, or local ordinances, Notifications.</li>
                        <li>To infringe upon or violate our intellectual property rights or the intellectual property rights of others.</li>
                        <li>To harass, abuse, insult, harm, defame, slander, disparage, intimidate, or discriminate based on gender, sexual orientation, religion, ethnicity, race, age, national origin, or disability.</li>
                        <li>To submit false or misleading information-any misrepresentations.</li>
                        <li>To upload or transmit viruses or any other type of malicious code or any unauthorized modification of the application that will or intent to be used in any way that will affect the functionality or operation of the Service or of any related mobile application, other mobile applications, or the Internet.</li>
                        <li>To collect or track the personal information of others.</li>
                        <li>To spam, phish, pretext, spider, crawl.</li>
                        <li>For any obscene or immoral purpose.</li>
                        <li>To interfere with or circumvent the security features of the Service or any related mobile application, other mobile applications, or the Internet.</li>
                    </ol>
                    <p>We reserve the right to terminate your use of the Service or any related mobile application for violating any of the prohibited uses and shall pursue legal remedies including claim damages against any loss of property, reputation, IPR, goodwill of Vidyutva Technology Private Limited or any of its stakeholders</p>
                </div>
                <p className="my-4">This Agreement does not transfer or assign to you any intellectual property owned by Vidyutva Technology Private Limited and all rights, titles, and interests in and to such related property will remain solely with Vidyutva Technology Private Limited. All trademarks, service marks, graphics and logos used in connection with our Mobile Application or Services, are trademarks or registered trademarks of Vidyutva Technology Private Limited. Other trademarks, service marks, graphics and logos used in connection with our Mobile Application or Services may be the trademarks of other third-parties. Your use of our Mobile Application and Services grants you no right or license to reproduce or otherwise use any Vidyutva Technology Private Limited.</p>
                <p className="my-4">The Services are provided on an "as is”, “as available" basis without any warranties whether express or implied. We will use reasonable endeavors to correct any errors or omissions as soon as practicable after being notified of them. However, we do not guarantee that the Services (Including vehicle charging), or the Mobile Application will be free of faults or error, and we do not accept liability for any such faults, errors or omissions. VIDYUTVA mobile application does not warrant that service descriptions and other content on the App are accurate, complete, reliable, current and error-free. In the event of any such error, fault or omission, you should report it by leaving a feedback to us on the mobile app. We do not warrant that your use of the Services or the Mobile Application will be uninterrupted and we do not warrant that any information (or messages) transmitted via the Mobile Application will be transmitted accurately, reliably, in a timely manner or at all. We will make best efforts to allow uninterrupted access to the Services, the Mobile Application. Notwithstanding anything to the contrary contained herein, access to the Services, and the Mobile Application may be suspended, restricted or terminated at any time. We do not give any warranty that the Services and the Mobile Application are free from viruses or anything else which may have a harmful effect on any technology. As a user, you make complete and independent assessment before purchasing the services from Vidyutva Technology Private Limited .For any additional help, you may visit our other sections of the App with your questions and seek help from our contact centre and report a feedback to us on the mobile app. You agree that the mobile application and any services are at your own risk and liability.</p>
                <p className="my-4">Charging services are being provided for common good. You should take utmost care of the devices while availing charging services. Vehicle should not be placed in the charging area other than your time of use. Any instructions laid out on the charging device or in the mobile application should be adhered to.</p>
                <div className="my-4">
                    <p>We reserve the right to terminate or suspend your User Account and/or the Services at any time without assigning any reason. Without prejudice to the generality of the foregoing, we reserve the right to terminate or suspend your use of the Services if:</p>
                    <ul className="pl-8 list-disc">
                        <li>There is abuse or misuse of the Services by you.</li>
                        <li>The vehicle is parked in the charging area at a time other than your scheduled charging times.</li>
                        <li>We are of the reasonable opinion that you have breached any of these Terms and Conditions.</li>
                        <li>We shall not be liable to you or to any other party for any damages, losses, cost or expenses howsoever caused by or arising out of such termination or suspension.</li>
                        <li>If we delete your account for the foregoing reasons, you may not be permitted to re-register for our Services. We may block/blacklist your email address and Internet protocol address to prevent further registration.</li>
                        <li>Upon the termination of any User Account, we reserve the right to delete from server(s) any information contained in the Mobile Application, including, but not limited to, postings, comments, bookmarks, messages, user ratings and points in account. There will be no refund to any kind on termination and you agree to waive all rights to claim or request of such refund. We reserves the right to block customers from using the App if the customer violates the terms and conditions.</li>
                        <li>No relaxation or delay by us in exercising any right or remedy under these Terms and Conditions of Service shall operate as waiver of that right or remedy or shall affect our ability to subsequently exercise that right or remedy. Any waiver must be agreed by us in writing.</li>
                    </ul>
                </div>
                <p className="my-4">We have the right to assign or transfer or sub-contract all or part of our rights or obligations here under these Terms and Conditions of Use at our discretion without prior notice to you. You may not assign or sub-contract any of your rights or obligations under these Terms and Conditions of Services to any third party unless we agree in writing. All rights and restrictions contained in this Agreement may be exercised and shall be applicable and binding only to the extent that they do not violate any applicable laws and are intended to be limited to the extent necessary so that they will not render this Agreement illegal, invalid or unenforceable. If any provision or portion of any provision of this Agreement shall be held to be illegal, invalid or unenforceable by a court of competent jurisdiction, it is the intention of the parties that the remaining provisions or portions thereof shall constitute their agreement with respect to the subject matter hereof, and all such remaining provisions or portions thereof shall remain in full force and effect.</p>
                <p className="my-4">You agree to indemnify and keep us indemnified against any claim, action, suit or proceeding brought or threatened to be brought against us which is caused by or arising out of (a) your use of the Services, (b) any other party’s use of the Services using your user ID, verification PIN and/or any identifier number allocated by us, and/or (c) your breach of any of these Terms and Conditions of Use, and you agree to pay us damages, costs and interest in connection with such claim, action, suit or proceeding.</p>
                <p className="my-4">The formation, interpretation, and performance of this Agreement and any disputes arising out of it shall be governed by the substantive and procedural laws of Kolkata, India without regard to its rules on conflicts or choice of law and, to the extent applicable, the laws of India. The exclusive jurisdiction and venue for actions related to the subject matter hereof shall be the courts located in Kolkata, India, and you hereby submit to the exclusive jurisdiction of such courts. You hereby waive any right to a jury trial in any proceeding arising out of or related to these terms and conditions.. The United Nations Convention on Contracts for the International Sale of Goods does not apply to this Agreement.</p>
                <p className="my-4">We reserve the right to modify the terms and conditions. or its policies relating to the Mobile Application or Services at any time to comply with the law or to meet our changing business requirements, effective upon posting of an updated version of this Agreement in the Mobile Application. When we do, we will revise the updated date at the bottom of this page. Continued use of the Mobile Application after any such changes shall constitute your consent to such changes. You acknowledge that you have read this Agreement and agree to all its terms and conditions. By using the Mobile Application or its Services you agree to be bound by this Agreement. If you do not agree to abide by the terms of this Agreement, you are not authorized to use or access the Mobile Application and its Services.</p>
                <p className="my-4">If you would like to contact us to understand more about these terms or wish to contact us concerning any matter relating to it, you may message us on the mobile application and we shall respond to you.</p>
                <p>Mail ID: <a href={`mailto:support@vidyutva.com`} className="text-blue-400">support@vidyutva.com</a></p>
                <p>This document was last updated on May 10, 2024.</p>
            </div>
            <Footer />
        </>
    )
}

export default termsConditions